var laureatDb=[
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        image:"peopl.png"

    },
    {
        id:2,
        firstName:"said",
        lastName:"magrani",
        promo:"2019-2021",
        ville:"settat",
        society:"sqli",
        location:"etranger",
        image:"peopl.png"
    },
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"etranger",
        image:"peopl.png"
    },
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"peopl.png"
    },
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"peopl.png"
    },
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"peopl.png"
    },
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"peopl.png"
    }

];

