var laureatDb=[
    {
        id:1,
        firstName:"abdessamade",
        lastName:"oukirce",
        promo:"2019-2021",
        ville:"sefrou",
        society:"Capgemini",
        location:"etranger",
        image:"man_2.png"

    },
    {
        id:2,
        firstName:"said",
        lastName:"marhrani",
        promo:"2017-2019",
        ville:"settat",
        society:"CGI FES",
        location:"etranger",
        image:"man.png"
    },
    {
        id:3,
        firstName:"John",
        lastName:"Doe",
        promo:"2013-2015",
        ville:"sefrou",
        society:"Atos",
        location:"etranger",
        image:"man_2.png"
    },
    {
        id:4,
        firstName:"Mark",
        lastName:"Smith",
        promo:"2019-2021",
        ville:"sefrou",
        society:"Umanis",
        location:"Maroc",
        image:"unknown_1.png"
    },
    {
        id:5,
        firstName:"James",
        lastName:"Bond",
        promo:"2019-2021",
        ville:"sefrou",
        society:"Atos",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:6,
        firstName:"Jason",
        lastName:"Stadham",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:7,
        firstName:"Ahmad",
        lastName:"Mohammed",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"man_2.png"
    },
    {
        id:8,
        firstName:"Ahmad",
        lastName:"Mohammed",
        promo:"2019-2021",
        ville:"sefrou",
        society:"atos",
        location:"maroc",
        image:"unknown_1.png"
    }

];

