var laureatDb=[
    {
        id:1,
        firstName:"Rida",
        lastName:"Elmansouri",
        promo:"2015",
        ville:"--",
        society:"Cegedime",
        location:"Maroc",
        image:"20190204_164413 - Riad EL MANSOUR.jpg"

    },
    {
        id:2,
        firstName:"Wafae",
        lastName:"Nabet",
        promo:"2020",
        ville:"Agadir",
        society:"CGI FES",
        location:"Maroc",
        image:"20191019_130926 - Wafae Nabet.jpg"
    },
    {
        id:3,
        firstName:"Selma",
        lastName:"Elmansour",
        promo:"2015",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"20180104_133311 - Selma Elmansour.jpg"
    },
    {
        id:4,
        firstName:"Ayoub",
        lastName:"Dadi",
        promo:"2016",
        ville:"--",
        society:"Umanis",
        location:"Maroc",
        image:"1572434108160 - ayoub dadi.jpg"
    },
    {
        id:5,
        firstName:"Safae",
        lastName:"Filali Sadiqi",
        promo:"2019",
        ville:"--",
        society:"Cegedim",
        location:"Maroc",
        image:"IMG_20190726_162514_0 - Filali Sadiq.jpg"
    },
    {
        id:6,
        firstName:"Hind",
        lastName:"Aalouch",
        promo:"2017",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:7,
        firstName:"Youness",
        lastName:"Mouhim",
        promo:"2016",
        ville:"--",
        society:"Umanis",
        location:"maroc",
        image:"man.png"
    },
    {
        id:8,
        firstName:"Mouad",
        lastName:"Youssef",
        promo:"2020",
        ville:"--",
        society:"SQLI",
        location:"maroc",
        image:"man.png"
    },
    {
        id:9,
        firstName:"Hicham",
        lastName:"Haidar",
        promo:"2019",
        ville:"--",
        society:"--",
        location:"france",
        image:"man.png"
    },
    {
        id: 10,
        firstName:"Fatima",
        lastName:"Zerkoun",
        promo:"2020",
        ville:"--",
        society:"CGI Technologie Fes ",
        location:"Maroc",
        image:"inbound3324569255492323171 - zerkoun fatima.jpg"
    },
    {
        id:11,
        firstName:"Badr",
        lastName:"Zeroual",
        promo:"2019",
        ville:"--",
        society:"CGI",
        location:"Maroc",
        image:"received_527627004337009 - Badr ZEROUAL.jpeg"
    },
    {
        id:12,
        firstName:"Ibtissam",
        lastName:"Elkhayri",
        promo:"2019",
        ville:"--",
        society:"BITS",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:13,
        firstName:"Aymane",
        lastName:"Hammioui",
        promo:"2018",
        ville:"--",
        society:"Salesforce",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:14,
        firstName:"Ghita",
        lastName:"Elhakimi",
        promo:"2019",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:15,
        firstName:"Ahmed",
        lastName:"Belarbi",
        promo:"2019",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:16,
        firstName:"Chaimae",
        lastName:"Laalahmi",
        promo:"2019",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:17,
        firstName:"Firdaous",
        lastName:"Khemlichi",
        promo:"2018",
        ville:"--",
        society:"CGI FES",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:18,
        firstName:"Mehdi",
        lastName:"Bennani",
        promo:"2017",
        ville:"--",
        society:"CGI FES",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:19,
        firstName:"Omar",
        lastName:"Boushabi",
        promo:"2017",
        ville:"--",
        society:"Capgemini",
        location:"Maroc",
        image:"man.png"
    },
    {
        id:20,
        firstName:"Kawtar",
        lastName:"Laazar",
        promo:"2016",
        ville:"--",
        society:"CGI FES",
        location:"Maroc",
        image:"man.png"
    }

];

